Fix Blockhound config for micrometer-context-propagation Since the ServiceLoader reads the files in a blocking way, Blockhound can detect these and cause java.lang.NoClassDefFoundError: Could not initialize class errors if the ServiceLoader is called from a static scope (static variable init or static block).